/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API Turnos Online
 * Documentacióin de la API para gestión de turnos y consultorios
 * OpenAPI spec version: 1.0.0
 */

export type PostAuth200 = {
  token?: string;
};
