/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * API Turnos Online
 * Documentacióin de la API para gestión de turnos y consultorios
 * OpenAPI spec version: 1.0.0
 */

export type UsuarioTipoUsuario = typeof UsuarioTipoUsuario[keyof typeof UsuarioTipoUsuario];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsuarioTipoUsuario = {
  NORMAL: 'NORMAL',
  PLUS: 'PLUS',
} as const;
